export const DB_NAME = "DigiMart";

export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "ERR_INTERNAL_SERVER",
  UNAUTHORIZED: "ERR_UNAUTHORIZED",
  FORBIDDEN: "ERR_FORBIDDEN",
  NOT_FOUND: "ERR_NOT_FOUND",
  BAD_REQUEST: "ERR_BAD_REQUEST",
  VALIDATION_ERROR: "ERR_VALIDATION",
  DUPLICATE_ENTRY: "ERR_DUPLICATE_ENTRY",
  INVALID_CREDENTIALS: "ERR_INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "ERR_TOKEN_EXPIRED",
  INVALID_TOKEN: "ERR_INVALID_TOKEN",
};

export const refreshTokenExpiryInMS =  1000 * 60 * 60 * 24 * 5